#!/usr/bin/env bash

set -x

if [ -z "$PROG" ]; then
    PROG="gdb --args"
fi

usage() {
    cat <<EOF
Usage: [PROG=<wrapper>] $0 <executable> [<args>]

Run a GHC "wrapped" executable in a debugger like gdb.
PROG="gdb --args" by default.

For instance,
    PROG=strace $0 ghc Hello.hs
EOF
}

exe="$1"
if [ -z "$exe" -o -z "$(which $exe)" ]; then
    usage
    exit 1;
fi
if [ ! -e "$(which $exe)" ]; then
    echo "$exe is not executable"
    echo
    usage
    exit 1
fi

wrapper="$(which $exe)"
shift
args="$@"

tmp=$(tempfile)
sed -e "s/exec /exec $PROG /" $wrapper > $tmp
cat $tmp
bash $tmp
rm $tmp
