#!/usr/bin/env python

import subprocess
from subprocess import check_call, check_output, Popen, PIPE
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('--dest', default='/opt/ghc')
parser.add_argument('--version', required=True)
parser.add_argument('--arch')
parser.add_argument('--dist')
args = parser.parse_args()

def detect_arch():
    out = check_output(['file', '/bin/bash'])
    kind = out.split(':')[1].strip()
    if kind.startswith('ELF 32-bit'):
        return 'i386'
    elif kind.startswith('ELF 64-bit'):
        return 'amd64'

arch = {
        'amd64': 'x86_64',
        'i386': 'i386',
        'x32': 'i386',
}.get(args.arch)
if arch is None:
    arch = detect_arch()

def detect_dist():
    a = open('/etc/issue').read()
    if a.startswith('Ubuntu'):
        return 'deb7'
    if a.startswith('Debian'):
        return 'deb7'
    if a.startswith('CentOS'):
        return 'centos65'

dist = args.dist
if dist is None:
    dist = detect_dist()

flavor="{arch}-unknown-linux-{dist}".format(arch=arch, dist=dist)

dest = os.path.join(args.dest, args.version)
check_call(['sudo', 'mkdir', '-p', args.dest])
user = check_output(['whoami']).strip()
check_call(['sudo', 'chown', user, args.dest])

url = "https://www.haskell.org/ghc/dist/{ver}/ghc-{ver}-{flavor}.tar.xz".format(ver=args.version, flavor=flavor)

download = Popen(['curl', '-L', url], stdout=subprocess.PIPE)
untar = Popen(['tar', '-Jx'], stdin=download.stdout)
untar.wait()

os.chdir('ghc-'+args.version)
check_call(['./configure', '--prefix={dest}'.format(dest=dest)])
check_call(['make', 'install'])

with open(os.path.join(dest, 'env.sh'), 'w') as f:
    f.write("""PATH={dest}/bin:$PATH
LD_LIBRARY_PATH={dest}/lib:$LD_LIBRARY_PATH
echo "Using GHC {ver}"
""".format(dest=dest, ver=args.version))
