#!/usr/bin/env bash

set -e

branch=$(git rev-parse --abbrev-ref HEAD)
utils=$(dirname $(realpath $0))

RED="\[\e[0;31m\]"
PURPLE="\[\e[0;35m\]"
NO_COLOUR="\[\e[0m\]"

for i in $@; do
        echo
        echo "Landing $i..."
        base=$(git rev-parse HEAD)
        git reset --hard
        git clean -f
        arc patch --skip-dependencies $i || (
            echo
            echo "Resolve the issue and commit or `exit 1`."
            PS1="${RED}resolve${NO_COLOR}(${PURPLE}$i${NO_COLOR}) $ " bash --norc -i
        )
        commit=$(git rev-parse HEAD)
        git checkout $branch
        git cherry-pick $commit
        git filter-branch -f --msg-filter "grep -v 'Summary:' | fold -s -w72" $base..$branch
        git checkout $base .gitmodules
        git commit --amend .gitmodules

        $utils/review-submodules

        echo
        echo "Landed $i"
        git diff --stat $base..$branch
done
