#!/bin/bash -e

./get-ghc --version=7.8.4
echo "PATH=$HOME/.cabal/bin:\$PATH" >>.bashrc
echo "source /opt/ghc/7.8.4/env.sh" >>.bashrc
echo "PS1=\"$DEST \$PS1\"" >>.bashrc
cabal update
cabal install cabal-install happy alex
git config --global user.name "Ben Gamari"
git config --global user.email "ben@well-typed.com"

cd
git clone git://git.haskell.org/ghc
cd ghc
git remote add bgamari https://bgamari@github.com/bgamari/ghc
git submodule update --init
./boot
./configure --prefix=/opt/ghc/root-ghc-head
