#!/bin/bash

if [ $# != 1 ]; then
    echo "Usage: $0 [COMMIT-RANGE]"
    exit 1
fi

commits=$(git rev-list $1)

log="validate-all.log"
echo "Validating $(echo "$commits" | wc -l) commits $1" | tee $log
echo "Started $(date)" | tee -a $log
echo | tee -a $log

function checkout() {
    commit=$1
    git checkout $1 || return $?
    git submodule update || return $?
}

function try() {
    label=$1
    shift
    $@
    ret=$?
    if [ $ret != 0 ]; then
        echo "Failed to $label ($ret)" | tee -a $log
    fi
    return $ret
}

function validate() {
    commit=$1
    echo -e "\nTesting $commit" | tee -a $log

    try "checkout" checkout $(echo "$commits" | head -n1) || exit 1
    if [ "x$force_clean" == "x1" ]; then
        try "validate" ./validate
    else
        if try "validate" ./validate --no-clean; then
            try "clean validate" ./validate || return $?
        fi
    fi
}

# Start with clean validation
if [ "x$no_clean" != "x1" ]; then force_clean=1; fi
commit=$(echo "$commits" | head -n1)
validate $commit $no_clean | tee validate-$commit.log
force_clean=0

for commit in $(echo "$commits" | tail -n1); do
    validate $commit | tee validate-$commit.log
done

echo "Finished $(date)" | tee -a $log
echo
echo
cat $log
