#!/bin/bash -e

cabal_ver="1.22.6.0"
src_url="https://www.haskell.org/cabal/release/cabal-install-$cabal_ver/cabal-install-$cabal_ver.tar.gz"

if [ "$OS" == "Windows_NT" -a ! -e $HOME/.cabal ]; then
    ln -s /c/Users/$(whoami)/AppData/Roaming/cabal $HOME/.cabal
fi

curl $src_url | tar -zx
cd $(basename ${src_url##/*/} .tar.gz)
./bootstrap.sh

$HOME/.cabal/bin/cabal update
echo "PATH=$HOME/.cabal/bin:\$PATH" >>$HOME/.bashrc
