#!/bin/bash -e

fname="cabal-install-1.22.6.0.tar.gz"
src_url="https://www.haskell.org/cabal/release/cabal-install-latest/$fname"
wget $src_url
tar -zxf $fname
cd $(basename ${src_url##/*/} .tar.gz)
./bootstrap.sh

$HOME/.cabal/bin/cabal update
echo "PATH=$HOME/.cabal/bin:\$PATH" >>$HOME/.bashrc
