#!/bin/bash -e

bootstrap=7.8.4

./get-ghc --version=$bootstrap

cd
echo "PATH=$HOME/.cabal/bin:\$PATH" >>.bashrc
echo "source /opt/ghc/$bootstrap/env.sh" >>.bashrc
cabal update
cabal install cabal-install happy alex hscolour
git config --global user.name "Ben Gamari"
git config --global user.email "ben@well-typed.com"

cd
git clone git://git.haskell.org/ghc
cd ghc
git remote add bgamari https://bgamari@github.com/bgamari/ghc
git submodule update --init
./boot
./configure --prefix=/opt/ghc/root-ghc-head
